# Generated by Django 5.2.6 on 2025-09-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='title',
            field=models.CharField(default='Home'),
        ),
    ]
