# Generated by Django 5.2.6 on 2025-09-18 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_productvariant_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Emoji, font-awesome class, or icon name', max_length=20)),
                ('color', models.CharField(choices=[('success', 'Success (Green)'), ('danger', 'Danger (Red)'), ('info', 'Info (Blue)'), ('warning', 'Warning (Yellow)'), ('primary', 'Primary'), ('secondary', 'Secondary')], default='primary', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='inventory.category')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('category', 'icon')},
            },
        ),
    ]
