# Generated by Django 5.2.6 on 2025-09-21 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_categoryicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Best_deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image_url', models.URLField()),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='inventory.productvariant')),
            ],
        ),
    ]
