# Generated by Django 5.2.6 on 2025-09-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='route',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
